# Generated by Django 4.2.7 on 2023-12-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0003_remove_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
