# Generated by Django 4.2.7 on 2023-12-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0005_remove_userprofile_email_remove_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
