# Generated by Django 4.2.7 on 2023-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0010_alter_userprofile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
