# Generated by Django 4.2.7 on 2023-12-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0013_userprofile_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
