# Generated by Django 4.2.7 on 2023-12-26 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0017_listing_ending_time_listing_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
