# Generated by Django 4.2.7 on 2023-12-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0018_alter_listing_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='end',
        ),
        migrations.AddField(
            model_name='transaction',
            name='end_hour',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_hour',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
