# Generated by Django 4.2.7 on 2023-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0019_remove_transaction_end_transaction_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=models.JSONField(default=list),
        ),
    ]
