# Generated by Django 4.2.7 on 2023-12-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0020_alter_listing_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ending_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
