# Generated by Django 4.2.7 on 2023-12-27 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0021_alter_listing_ending_time_alter_listing_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='start_hour',
        ),
        migrations.AddField(
            model_name='transaction',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
