# Generated by Django 4.2.7 on 2023-12-27 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0022_remove_listing_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='end',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='start',
        ),
        migrations.AddField(
            model_name='transaction',
            name='end_hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
