# Generated by Django 4.2.7 on 2023-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0023_remove_transaction_end_remove_transaction_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=646999377205),
        ),
    ]
