# Generated by Django 4.2.7 on 2023-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0027_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoiceId',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=929688811809, unique=True),
        ),
    ]
