# Generated by Django 4.2.7 on 2023-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0028_transaction_invoiceid_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=672677841495, unique=True),
        ),
    ]
