# Generated by Django 4.2.7 on 2023-12-27 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareplay', '0029_game_views_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(blank=True, default=5, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=910095148448, unique=True),
        ),
    ]
