# Generated by Django 4.2.7 on 2023-12-28 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareplay', '0030_remove_game_owner_game_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_transactions', to='shareplay.game'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=543361775330, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rented_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rented_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
