# Generated by Django 4.2.7 on 2023-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0031_alter_transaction_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='session_id',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=969846914840, unique=True),
        ),
    ]
