# Generated by Django 4.2.7 on 2023-12-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0032_listing_session_id_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='session_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='session_id',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=531844712760, unique=True),
        ),
    ]
