# Generated by Django 4.2.7 on 2023-12-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareplay', '0033_remove_listing_session_id_transaction_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=961860180743, unique=True),
        ),
        migrations.CreateModel(
            name='RateStreamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('contewnt', models.TextField()),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
