# Generated by Django 4.2.7 on 2023-12-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0034_alter_transaction_randomnumber_ratestreamer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratestreamer',
            old_name='contewnt',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=870487462516, unique=True),
        ),
    ]
