# Generated by Django 4.2.7 on 2023-12-28 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareplay', '0035_rename_contewnt_ratestreamer_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratestreamer',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='shareplay.game'),
        ),
        migrations.AlterField(
            model_name='ratestreamer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=176894230052, unique=True),
        ),
    ]
