# Generated by Django 4.2.7 on 2023-12-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0037_transaction_isplayable_transaction_isittoday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=91685213270, unique=True),
        ),
    ]
