# Generated by Django 4.2.7 on 2023-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0038_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isPlayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=559911403714, unique=True),
        ),
    ]
