# Generated by Django 4.2.7 on 2023-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0039_transaction_isplayed_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=330933768869, unique=True),
        ),
    ]
