# Generated by Django 4.2.7 on 2023-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0042_ratestreamermodel_alter_transaction_randomnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notExpied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=911851193335, unique=True),
        ),
    ]
