# Generated by Django 4.2.7 on 2023-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0043_transaction_notexpied_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=254141249100, unique=True),
        ),
    ]
