# Generated by Django 4.2.7 on 2023-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0047_userprofile_isrevenueprivate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=669637131508, unique=True),
        ),
    ]
