# Generated by Django 4.2.7 on 2023-12-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0048_transaction_revenue_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=613021807624, unique=True),
        ),
    ]
