# Generated by Django 4.2.7 on 2023-12-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0049_alter_game_slug_alter_transaction_randomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ListId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=607394613260, unique=True),
        ),
    ]
