# Generated by Django 4.2.7 on 2023-12-30 15:47

from django.db import migrations, models
import shareplay.models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0050_transaction_listid_alter_game_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ListId',
            field=models.IntegerField(default=0, verbose_name=shareplay.models.Listing),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=384972050650, unique=True),
        ),
    ]
