# Generated by Django 4.2.7 on 2023-12-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay', '0052_alter_transaction_listid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ListId',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ListId', to='shareplay.listing'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='randomNumber',
            field=models.IntegerField(default=989503069292, unique=True),
        ),
    ]
